### ISSUE TITLE
error in compile

### ISSUE THREAD

**Issue by ertaj** [Mds92/mds-angular-datetime-picker-package#1]
hi thanks for your nice project.
but when compile the project error was happen ! (class not found)
please fixed that !

**Comment by Mds92** [comment]
Please describe more!
Please post  the error message

**Comment by unseen-code** [comment]
use cmd 
npm install mds.angular.datetimepicker@latest --save
![11111](https://user-images.githubusercontent.com/29938546/32029955-44826b8c-ba2a-11e7-81ca-0da14de66a57.PNG)

**Comment by Mds92** [comment]
`mds.angular.datetimepicker` Use the following library, install it too:
https://github.com/Mds92/mds-persian-datetime-package

**Comment by behroozbc** [comment]
hi 
i have new error 
![screenshot 12](https://user-images.githubusercontent.com/20381616/38048283-288b7738-32da-11e8-9d05-6edbb6ce2a06.png)
i use Angular CLI version (1.7.3)
thanks

**Comment by Mds92** [comment]
Please get latest version
