### ISSUE TITLE
Module build failed:

### ISSUE THREAD

**Issue by khaterehsb** [Mds92/mds-angular-datetime-picker-package#3]

**Comment by khaterehsb** [comment]
ERROR in ../node_modules/mds.angular.datetimepicker/components/core/mds-datetime-picker-core.component.ts
Module build failed: Error: node_modules\mds.angular.datetimepicker\components\core\mds-datetime-picker-core.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

**Comment by Mds92** [comment]
This library not supported and I have to update it to angular 6

**Comment by Mds92** [comment]
You can use it in Angular 6+ now
Get latest version
