### ISSUE TITLE
خواندن مقدار ورودی کاربر

### ISSUE THREAD

**Issue by Alirezamohammadi** [Mds92/mds-angular-datetime-picker-package#5]
سلام، من ماژول رو داخل برنامه ایمپورت کردم و به درستی هم داره کار میده ولی خب مشکل اصلی اینجاس که توی داکیومنت توضیح ندادید مقدار رو چجوری باید بخونیم و داخل کامپوننت ازش استفاده کنیم، من طبق معمول بقیه اینپوت ها به این صورت عمل کردم:
`<mds-angular-persian-datetimepicker name="birthdayDate" ng-reflect-model (ngModel)]="preReg.birthdayDate" #birthdayDate="ngModel"
                  [inLine]="false" [timePicker]="false" [placeHolder]="'مثال: ۱۳۹۰/۰۵/۰۲'">
</mds-angular-persian-datetimepicker>`
الان من اون طرف دسترسی به این مقدار این مدلی که روی این تعریف کردم ندارم و کنسول مرورگر هم داره این ارور رو بهم میده:
`ERROR Error: Uncaught (in promise): Error: No value accessor for form control with name: 'birthdayDate'`
اگه ممکنه بررسی کنید خیلی ممنون.

**Comment by Alirezamohammadi** [comment]
ممنونم بسیار بسیار لطف می‌کنید.
کمتر توسعه دهنده ای از داخل مانند شما دیدم که ماژول های اوپن سورس به این کیفیت در دسترس عموم قرار دهد.
کارتان بسیار قابل تحسین است👍
سپاسگزارم

**Comment by Mds92** [comment]
ممنون از شما
لطفا آخرین ورژن را دریافت و تست نمائید

**Comment by Alirezamohammadi** [comment]
آقا یک دنیا تشکر بابت این رسیدگی فوق سریعتون.
آپدیت کردم و الان بدون مشکل کار می‌کنه.

**Comment by Alirezamohammadi** [comment]
انشالله بتونیم افراد بیشتری مثل شما تو جامعه اوپن سورس کشورمون داشته باشیم👌👏

**Comment by Mds92** [comment]
با تشکر از شما
انشالا
